# Setup
title:     'Paglia.org'
baseurl:   ""
url: ""

# About/contact
author:
  name:       Lido Paglia
  url:        https://paglia.org
  email:      lido@paglia.org
  github:     lidopaglia
  instagram:  lidopaglia
  linkedin:   lidopaglia
  twitter:    nicemarmot

# Conversion
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock